// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV1FQmxHIjVj1RUS0HAfLrcKwV3ZoDogs',
    appId: '1:62951559901:web:46e40b10b70ce69c690134',
    messagingSenderId: '62951559901',
    projectId: 'remakecan-afaa9',
    authDomain: 'remakecan-afaa9.firebaseapp.com',
    databaseURL: 'https://remakecan-afaa9-default-rtdb.firebaseio.com',
    storageBucket: 'remakecan-afaa9.appspot.com',
    measurementId: 'G-NF6PQJV72F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC045bkJYbQaAaGpDyBsM-7Q4-mzzlDY5c',
    appId: '1:62951559901:android:f3f30edce55e07fc690134',
    messagingSenderId: '62951559901',
    projectId: 'remakecan-afaa9',
    databaseURL: 'https://remakecan-afaa9-default-rtdb.firebaseio.com',
    storageBucket: 'remakecan-afaa9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr3cFZcRDo8iP7YyUB9ZUMx6myWW4W8D8',
    appId: '1:62951559901:ios:42c5e052affeed1a690134',
    messagingSenderId: '62951559901',
    projectId: 'remakecan-afaa9',
    databaseURL: 'https://remakecan-afaa9-default-rtdb.firebaseio.com',
    storageBucket: 'remakecan-afaa9.appspot.com',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr3cFZcRDo8iP7YyUB9ZUMx6myWW4W8D8',
    appId: '1:62951559901:ios:42c5e052affeed1a690134',
    messagingSenderId: '62951559901',
    projectId: 'remakecan-afaa9',
    databaseURL: 'https://remakecan-afaa9-default-rtdb.firebaseio.com',
    storageBucket: 'remakecan-afaa9.appspot.com',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV1FQmxHIjVj1RUS0HAfLrcKwV3ZoDogs',
    appId: '1:62951559901:web:06b40d75a9447032690134',
    messagingSenderId: '62951559901',
    projectId: 'remakecan-afaa9',
    authDomain: 'remakecan-afaa9.firebaseapp.com',
    databaseURL: 'https://remakecan-afaa9-default-rtdb.firebaseio.com',
    storageBucket: 'remakecan-afaa9.appspot.com',
    measurementId: 'G-529LJM1WJ5',
  );
}
